------CREATE TABLE----
CREATE TABLE PESSOA(
ID_PESSOA integer primary key not null,
NOME varchar2(500),
EMAIL varchar2(500),
ACEITO char(1),
DATA_CADASTRO date
);COMMIT;

INSERT INTO PESSOA VALUES(1,'WELLINGTON','WELL@GMAIL.COM','1','25/08/15');
INSERT INTO PESSOA VALUES(2,'JOSE','JOSE@GMAIL.COM','1','15/09/16');
INSERT INTO PESSOA VALUES(3,'RAFAEL','RAFAEL@GMAIL.COM','0','25/08/17');
INSERT INTO PESSOA VALUES(4,'JOAO','JOAO@GMAIL.COM','0','05/09/17');
COMMIT;

DROP TABLE PESSOA;